### PR TITLE
automate publishing npm

### PR DESCRIPTION
**Pull request by USAMAWIZARD**
added a script that automates the process of publishing a snapshot version of JS SDK to npm repository.

### CODE REVIEW

**Comment by USAMAWIZARD** [comment]
I cannot figure out why the npm unpublished does not unpublished the previous library 
There is no error log when I run this command on the CI side but the package  version is not unpublished
image

But when I run the same command on my local env its working fine the package gets unpublished
image

I suspect npm unpublish may require the account to be longed in 

here you can see the CI pipeline
https://github.com/USAMAWIZARD/npmpublishtest/actions/runs/4206453363/jobs/7299955130

**Comment by mustafaboleken** [comment]
@USAMAWIZARD before I review the implementation, could you please give me information about the unpublish error? Is it fixed or still persist?

**Comment by mekya** [comment]
Hey @USAMAWIZARD ,

Please mention which issue you're resolving in this PR in order to follow up and generate a good changelog?

**Comment by USAMAWIZARD** [comment]
@mustafaboleken npm unpublish does not give any error on the ci side here
[here ](https://github.com/USAMAWIZARD/npmpublishtest/actions/runs/4206453363/jobs/7299955130)  is the link to the running ci pipeline 

> I cannot figure out why the npm unpublished does not unpublished the previous library ( when its run on CI side). There is no error log when I run this command on the CI side but the package version is not unpublished image
> 
> But when I run the same command on my local env its working fine the package gets unpublished image
> 
> I suspect npm unpublish may require the account to be longed in
> 
> here you can see the CI pipeline https://github.com/USAMAWIZARD/npmpublishtest/actions/runs/4206453363/jobs/7299955130

https://github.com/ant-media/StreamApp/pull/339#issuecomment-1435088318

**Comment by mustafaboleken** [comment]
@USAMAWIZARD There are some problems please check them:

1- echo "PREVIOUS_SNAPSHOT_VERSION not working
2- I cannot display published version on npm 

https://github.com/ant-media/StreamApp/actions/runs/4294039452/jobs/7482749611

**Comment by USAMAWIZARD** [comment]
- run: echo "PREVIOUS_SNAPSHOT_VERSION=$(npm view ${{ secrets.NPM_USERNAME }}/test dist-tags --json | jq .SNAPSHOT --raw-output)" >> $GITHUB_ENV	

that command is something like this 
did add the NPM_USERNAME As a secret in github

**Comment by mustafaboleken** [comment]
> * run: echo "PREVIOUS_SNAPSHOT_VERSION=$(npm view ${{ secrets.NPM_USERNAME }}/test dist-tags --json | jq .SNAPSHOT --raw-output)" >> $GITHUB_ENV
> 
> that command is something like this did add the NPM_USERNAME As a secret in github

I don't have access to see secret on repository. Please contact with @mekya and be sure required information are added.

**Comment by USAMAWIZARD** [comment]
sure

**Comment by USAMAWIZARD** [comment]
antmedia is the username for the npmjs you can do something like this

echo "PREVIOUS_SNAPSHOT_VERSION=$(npm view @antmedia/test dist-tags --json | jq .SNAPSHOT --raw-output)" >> $GITHUB_ENV

**Comment by USAMAWIZARD** [comment]
Did unpublished worked your you ??

**Comment by mustafaboleken** [comment]
@USAMAWIZARD unpublish feature is not working right now.

**Comment by asharamseervi** [comment]
Hi @USAMAWIZARD & @mustafaboleken; Probably unpublishing isn't working due to these [npm Unpublish Policy](https://docs.npmjs.com/policies/unpublish#packages-published-more-than-72-hours-ago). Could you let me know, if you checked this?

Otherwise, you may try adding the owner name as illustrated [here](https://docs.npmjs.com/policies/unpublish#what-to-do-if-your-package-does-not-meet-the-unpublish-criteria)
> ```npm owner add npm <package>```

**Comment by mustafaboleken** [comment]
> Hi @USAMAWIZARD & @mustafaboleken; Probably unpublishing isn't working due to these [npm Unpublish Policy](https://docs.npmjs.com/policies/unpublish#packages-published-more-than-72-hours-ago). Could you let me know, if you checked this?
> 
> Otherwise, you may try adding the owner name as illustrated [here](https://docs.npmjs.com/policies/unpublish#what-to-do-if-your-package-does-not-meet-the-unpublish-criteria)
> 
> > `npm owner add npm <package>`

We are aware of these requirements, but unpublish worked without any problem on terminal but not working on cli.

**Review by mustafaboleken — APPROVED** [review]

**Pull request merged**
