### PR TITLE
Refactor/constraints

### PR DESCRIPTION
**Pull request by golgetahir**

### CODE REVIEW

**Review by mekya — CHANGES_REQUESTED** [review]
Could you please fix the conflict in the code?

**Comment by elishevak1** [comment]
Hi
Will this PR be merged in next version?
I need a way to get video only on the stream and this code looks like what I looked for..
thanks
P.S. is there a way to do the opposite? I mean get audio only on the stream?

**Comment by elishevak1** [comment]
Hi @golgetahir 
Thanks for your answer! I'll wait patiently for your improvements.
Maybe my question wasn't clear enough... I meat: while publisher is publishing both audio and video - is it possible to ask audio only / video only on the stream in client side? as a throughput optimization?
thanks again!

**Comment by golgetahir** [comment]
Hi @elishevak1 

My pleasure and thank you for using Ant Media.

Yes your question is available, check out toggleVideo and toggleAudio commands : https://github.com/ant-media/Ant-Media-Server/wiki/WebRTC-WebSocket-Messaging-Reference#playing-webrtc-stream

**Comment by mustafaboleken** [comment]
This pr is outdated and I'm closing it

**Pull request closed without merging**
