### PR TITLE
Refactor TypeScript Pipeline

### PR DESCRIPTION
**Pull request by mustafaboleken**
https://github.com/ant-media/Ant-Media-Server/issues/5066

### CODE REVIEW

**Review by USAMAWIZARD — APPROVED** [review]

**Comment by mekya** [comment]
I expect a type definition file. Do you let me know where it's?

Secondly having a separate `TSsample` directory at the top does not look good to me. Is it mandatory?

**Comment by mustafaboleken** [comment]
Normally I'm the reviewer of the another pull request. I made some changes and merge it but I forget to commit the changes. So I created this pr. @mekya

**Comment by mustafaboleken** [comment]
Index.d.at file created automatically inside dist/es folder dynamically. Should we make it static?

**Comment by mekya** [comment]
If it's generated dynamically, it's better. Congrats 👏

**Pull request merged**
