### PR TITLE
Fix checkWebSocketConnection checkpoint

### PR DESCRIPTION
**Pull request by SelimEmre**
Use `isWebSocketTriggered` instead of `isConnected`.

### CODE REVIEW

**Review by eneskuluk — COMMENTED** [review]
This PR looks like resolves the problem with this issue: https://github.com/ant-media/Ant-Media-Server/issues/3408
As far as my testing this does not break integrity. If you have some idea that this pr can broke, let me know so that i can test it.

**Comment by tkdave** [comment]
`isWebSocketTriggered` is a property used on websocketadaptor, but it is declared on webrtcadaptor. This code appears to accidentally fix the issue. Code is a bit messy here. I would review a bit more closely.

**Review by mekya — CHANGES_REQUESTED** [review]
There are two `isWebSocketTriggered` in both WebRTCAdaptor and WebSocketAdaptor. Its value is not changed in anywhere else. I don't think this is a proper solution

**Review by mekya — APPROVED** [review]

**Comment by tkdave** [comment]
Much better after refactor with connecting state. looks good. thanks, @mekya

**Comment by mekya** [comment]
My pleasure.

Take care

**Pull request merged**
