### PR TITLE
Remove useless mapping causes error from popper library

### PR DESCRIPTION
**Pull request by golgetahir**
https://github.com/ant-media/Ant-Media-Server/issues/3729

### CODE REVIEW

**Comment by mekya** [comment]
Are you sure it's removing the bootstrap.min.js.map? I don't think so

**Review by mekya — CHANGES_REQUESTED** [review]
Are you sure it's removing the bootstrap.min.js.map? I don't think so

**Comment by golgetahir** [comment]
From a comment:
https://stackoverflow.com/questions/21773376/bootstrap-trying-to-load-map-file-how-to-disable-it-do-i-need-to-do-it


.map files allow a browser to download a full version of the minified JS. It is really for debugging purposes.

In effect, the .map missing isn't a problem. You only know it is missing, as the browser has had its Developer tools opened, detected a minified file and is just informing you that the JS debugging won't be as good as it could be.

This is why libraries like jQuery have the full, the minified and the map file too.

See this article for a full explanation of .map files:

**Comment by mekya** [comment]
Thank you for making it clear for me. 

My point is that the issue is about bootstrap  map [ant-media/Ant-Media-Server#3729](https://github.com/ant-media/Ant-Media-Server/issues/3729)

You just remove commented line in the file changes.

**Review by mekya — APPROVED** [review]

**Comment by mekya** [comment]
OK. Merging

**Pull request merged**
